#!/usr/bin/python

import os
import rpm
import sys
import gtk

cur_url = sys.argv[0][:-15]

#JSH: for processing korean...
from rhpl.translate import _, textdomain, addPoPath

#for processing korean...
os.environ["LANG"] = "ko_KP.UTF-8"
from rhpl.translate import _, textdomain, addPoPath
try:
    os.system("cp %s/translate.mo /usr/share/locale/ko_KP/LC_MESSAGES/hdinstall.mo -f" % cur_url )
except:
    print "can not copy translate file..."
textdomain("hdinstall")    

realpath = ""
path = ""

#log = os.open("/dev/tty3", os.O_WRONLY)
#os.dup2(log, 1)
#os.dup2(log, 2)
#os.close(log)

def basepath():
    global realpath
    cwd = os.getcwd()
    
    if not os.environ.has_key('SOURCEPATH'):
    	print "Can not get environment."
    	sys.exit(0)
    exepath = os.path.realpath(os.environ['SOURCEPATH'])
    if exepath.startswith('/'):
    	realpath = exepath[:-8]
    elif exepath.startswith('./'):
    	realpath = cwd + "/" + exepath[2:-8]
    else:
    	realpath = cwd + "/" + exepath[:-8]

def start_window_manager():
    wm_pid = os.fork()

    if (not wm_pid):
        path = '/usr/bin/metacity'
        args = ['--display=:1']
        os.execvp(path, args)

    status = 0
    try:
        pid, status = os.waitpid (wm_pid, os.WNOHANG)

    except OSError, (errno, msg):
        print "in except"
        print __name__, "waitpid:", msg

    if status:
        raise RuntimeError, "Window manager failed to start"

    return wm_pid

def main(argv):

    import foundation
    import constants
    global realpath

    if os.environ.has_key('PRODDEV') and os.environ.has_key('PRODPATH'):
    	constants.rebooted = True

#    start_window_manager()

    gtk.rc_parse( "%s/theme/gtkrc" % cur_url)

    os.system("xsetroot -cursor_name left_ptr")

    constants.realpath = realpath

    maindlg = foundation.foundation()
    maindlg.getscreen()

if __name__ == "__main__":
    run = 1
    basepath()
    #for RS2.0 with normal user
    try:
	if os.access("/etc/redstar-release", os.R_OK ):
    	    f = open("/etc/redstar-release", "r")
    	    if f:
    		if f.read().__contains__("2.0"):
    	    	    if not os.environ["USER"] == "root":
    	    		os.system('kdialog --caption "Install Error" --error "Can not install with normal user"')
    			run = 0
    except:
	pass
    
    if run:
    	sys.path.append(cur_url)
	main(sys.argv)
        gtk.main()
